In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the dataset
df = pd.read_excel('The_code_change_defects.xlsx')

# Perform tokenization and vectorization (TF-IDF) on the code snippets
vectorizer = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b")
tfidf_matrix = vectorizer.fit_transform(df['code_change_snippet'])

# The 'tfidf_matrix' is a sparse matrix containing the TF-IDF weights
# Let's convert this matrix to a DataFrame for better readability
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

tfidf_df.head(10)

c:\Users\warun\anaconda3\envs\tensorflow\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\warun\anaconda3\envs\tensorflow\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\warun\anaconda3\envs\tensorflow\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

,0,05,1,10,1000,15,2,200,5,__init__,...,valid,validate_email,validate_input,value,valueerror,while,with,x,y,zerodivisionerror
0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.228689,0.000000,0.0,0.000000,...,0.0,0.000000,0.228689,0.0,0.121808,0.000000,0.000000,0.0,0.0,0.0
1,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.186957,0.000000,0.0,0.182785,0.000000,0.000000,0.0,0.0,0.0
3,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.193114,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
4,0.156752,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
5,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
6,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.194058,0.0,0.0,0.0
7,0.190678,0.0,0.104208,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
8,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.206183,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
9,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.102027,...,0.0,0.000000,0.000000,0.0,0.000000,0.111656,0.000000,0.0,0.0,0.0

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load your DataFrame from the Excel file
df = pd.read_excel('The_code_change_defects.xlsx')

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# Fit and transform the "defect_description" column
df['defect_description_encoded'] = label_encoder.fit_transform(df['defect_description'])

# Display the encoded DataFrame
print(df[['defect_description', 'defect_description_encoded']])

                           defect_description  defect_description_encoded
0   ValueError not caught in the calling code                          30
1                Division by zero not handled                           4
2                  Notification sending error                          21
3     Sensitive password stored in plain text                          24
4          Potential index out of range error                          23
..                                        ...                         ...
75                  Possible division by zero                          22
76                                ImportError                           7
77                           IndentationError                          15
78                                 ValueError                          29
79                          ZeroDivisionError                          31

[80 rows x 2 columns]